server:
  port: 8003

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/em}
    username: ${DB_USER:emuser}
    password: ${DB_PASSWORD:empassword}
    driver-class-name: org.postgresql.Driver
  jpa:

    database-platform: org.hibernate.dialect.PostgreSQLDialect

    generate-ddl: false
    hibernate:
      ddl-auto: none

    show-sql: false
    properties:
      hibernate:
        format_sql: true
  sql.init.mode: never

vtb.api:
  branch:
    url: https://headless-cms3.vtb.ru/projects/atm/models/default/items/departments
  atm:
    url: https://online.vtb.ru/msa/api-gw/attm/attm-dictionary/atm/nearby/filtered/
    referer: https://online.vtb.ru/map/atms/
    radius: 15

places:
  radius: 10000
  limit: 300

atm.bank.titles:
  "VTB": "ВТБ"
  "OPEN": "Банк Открытие"
  "LETO_BANK": "Лето Банк"


springdoc:

  api-docs.path: /places/api-docs

  swagger-ui:
    url: https://localhost/swagger-ui/
    urls:
      - name: Places
        url: /places/api-docs
        display-name: Отделения и банкоматы
      - name: routes
        url: /routes/api-docs
        display-name: Маршруты
      - name: lines
        url: /lines/api-docs
        display-name: Статистика очередей